// <auto-generated />
using System;
using ClarifEye.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClarifEye.Data.Migrations
{
    [DbContext(typeof(ClarifEyeDbContext))]
    [Migration("20250531080730_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClarifEye.Data.Models.Choice", b =>
                {
                    b.Property<int>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChoiceId"));

                    b.Property<string>("AnswerString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MultipleChoiceQuestionId")
                        .HasColumnType("int");

                    b.HasKey("ChoiceId");

                    b.HasIndex("MultipleChoiceQuestionId");

                    b.ToTable("Choices");

                    b.HasData(
                        new
                        {
                            ChoiceId = 1,
                            AnswerString = "Less than 1 year ago",
                            MultipleChoiceQuestionId = 1
                        },
                        new
                        {
                            ChoiceId = 2,
                            AnswerString = "1–2 years ago",
                            MultipleChoiceQuestionId = 1
                        },
                        new
                        {
                            ChoiceId = 3,
                            AnswerString = "More than 2 years ago",
                            MultipleChoiceQuestionId = 1
                        });
                });

            modelBuilder.Entity("ClarifEye.Data.Models.ChoiceAnswer", b =>
                {
                    b.Property<int>("ChoiceAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChoiceAnswerId"));

                    b.Property<int>("ChoiceId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ChoiceAnswerId");

                    b.HasIndex("ChoiceId");

                    b.HasIndex("UserId");

                    b.ToTable("ChoiceAnswers");

                    b.HasData(
                        new
                        {
                            ChoiceAnswerId = 1,
                            ChoiceId = 1,
                            UserId = "user-1"
                        },
                        new
                        {
                            ChoiceAnswerId = 2,
                            ChoiceId = 2,
                            UserId = "user-2"
                        },
                        new
                        {
                            ChoiceAnswerId = 3,
                            ChoiceId = 3,
                            UserId = "user-3"
                        },
                        new
                        {
                            ChoiceAnswerId = 4,
                            ChoiceId = 2,
                            UserId = "user-5"
                        });
                });

            modelBuilder.Entity("ClarifEye.Data.Models.MultipleChoiceQuestion", b =>
                {
                    b.Property<int>("MultipleChoiceQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MultipleChoiceQuestionId"));

                    b.Property<string>("QuestionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MultipleChoiceQuestionId");

                    b.ToTable("MultipleChoiceQuestions");

                    b.HasData(
                        new
                        {
                            MultipleChoiceQuestionId = 1,
                            QuestionString = "When was your last eye exam?"
                        });
                });

            modelBuilder.Entity("ClarifEye.Data.Models.ScaleAnswer", b =>
                {
                    b.Property<int>("ScaleAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScaleAnswerId"));

                    b.Property<string>("ClarUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ScaleQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedOption")
                        .HasColumnType("int");

                    b.HasKey("ScaleAnswerId");

                    b.HasIndex("ClarUserId");

                    b.HasIndex("ScaleQuestionId");

                    b.ToTable("ScaleAnswers");

                    b.HasData(
                        new
                        {
                            ScaleAnswerId = 1,
                            ClarUserId = "user-1",
                            ScaleQuestionId = 1,
                            SelectedOption = 0
                        },
                        new
                        {
                            ScaleAnswerId = 2,
                            ClarUserId = "user-1",
                            ScaleQuestionId = 2,
                            SelectedOption = 0
                        },
                        new
                        {
                            ScaleAnswerId = 3,
                            ClarUserId = "user-1",
                            ScaleQuestionId = 3,
                            SelectedOption = 0
                        },
                        new
                        {
                            ScaleAnswerId = 4,
                            ClarUserId = "user-1",
                            ScaleQuestionId = 4,
                            SelectedOption = 0
                        },
                        new
                        {
                            ScaleAnswerId = 5,
                            ClarUserId = "user-1",
                            ScaleQuestionId = 5,
                            SelectedOption = 0
                        },
                        new
                        {
                            ScaleAnswerId = 6,
                            ClarUserId = "user-1",
                            ScaleQuestionId = 6,
                            SelectedOption = 0
                        },
                        new
                        {
                            ScaleAnswerId = 7,
                            ClarUserId = "user-1",
                            ScaleQuestionId = 7,
                            SelectedOption = 0
                        },
                        new
                        {
                            ScaleAnswerId = 8,
                            ClarUserId = "user-1",
                            ScaleQuestionId = 8,
                            SelectedOption = 0
                        },
                        new
                        {
                            ScaleAnswerId = 9,
                            ClarUserId = "user-1",
                            ScaleQuestionId = 9,
                            SelectedOption = 0
                        },
                        new
                        {
                            ScaleAnswerId = 10,
                            ClarUserId = "user-1",
                            ScaleQuestionId = 10,
                            SelectedOption = 0
                        },
                        new
                        {
                            ScaleAnswerId = 11,
                            ClarUserId = "user-1",
                            ScaleQuestionId = 11,
                            SelectedOption = 0
                        },
                        new
                        {
                            ScaleAnswerId = 12,
                            ClarUserId = "user-1",
                            ScaleQuestionId = 12,
                            SelectedOption = 0
                        },
                        new
                        {
                            ScaleAnswerId = 13,
                            ClarUserId = "user-1",
                            ScaleQuestionId = 13,
                            SelectedOption = 0
                        });
                });

            modelBuilder.Entity("ClarifEye.Data.Models.ScaleQuestion", b =>
                {
                    b.Property<int>("ScaleQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScaleQuestionId"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScaleQuestionId");

                    b.ToTable("ScaleQuestions");

                    b.HasData(
                        new
                        {
                            ScaleQuestionId = 1,
                            QuestionText = "Blurry vision"
                        },
                        new
                        {
                            ScaleQuestionId = 2,
                            QuestionText = "Double vision"
                        },
                        new
                        {
                            ScaleQuestionId = 3,
                            QuestionText = "Difficulty seeing at night"
                        },
                        new
                        {
                            ScaleQuestionId = 4,
                            QuestionText = "Halos around lights"
                        },
                        new
                        {
                            ScaleQuestionId = 5,
                            QuestionText = "Trouble focusing"
                        },
                        new
                        {
                            ScaleQuestionId = 6,
                            QuestionText = "Dry or gritty eyes"
                        },
                        new
                        {
                            ScaleQuestionId = 7,
                            QuestionText = "Watery eyes"
                        },
                        new
                        {
                            ScaleQuestionId = 8,
                            QuestionText = "Red or bloodshot eyes"
                        },
                        new
                        {
                            ScaleQuestionId = 9,
                            QuestionText = "Burning/itching"
                        },
                        new
                        {
                            ScaleQuestionId = 10,
                            QuestionText = "Eye pain or pressure"
                        },
                        new
                        {
                            ScaleQuestionId = 11,
                            QuestionText = "Headaches after screens"
                        },
                        new
                        {
                            ScaleQuestionId = 12,
                            QuestionText = "Eye strain or tiredness"
                        },
                        new
                        {
                            ScaleQuestionId = 13,
                            QuestionText = "Sensitivity to light"
                        });
                });

            modelBuilder.Entity("ClarifEye.Data.Models.YesNoAnswer", b =>
                {
                    b.Property<int>("YesNoAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YesNoAnswerId"));

                    b.Property<string>("ClarUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SelectedOption")
                        .HasColumnType("int");

                    b.Property<int>("YesNoQuestionId")
                        .HasColumnType("int");

                    b.HasKey("YesNoAnswerId");

                    b.HasIndex("ClarUserId");

                    b.HasIndex("YesNoQuestionId");

                    b.ToTable("YesNoAnswers");

                    b.HasData(
                        new
                        {
                            YesNoAnswerId = 1,
                            ClarUserId = "user-1",
                            SelectedOption = 1,
                            YesNoQuestionId = 1
                        },
                        new
                        {
                            YesNoAnswerId = 2,
                            ClarUserId = "user-1",
                            SelectedOption = 1,
                            YesNoQuestionId = 2
                        },
                        new
                        {
                            YesNoAnswerId = 3,
                            ClarUserId = "user-1",
                            SelectedOption = 0,
                            YesNoQuestionId = 3
                        },
                        new
                        {
                            YesNoAnswerId = 4,
                            ClarUserId = "user-1",
                            SelectedOption = 1,
                            YesNoQuestionId = 4
                        },
                        new
                        {
                            YesNoAnswerId = 5,
                            ClarUserId = "user-1",
                            SelectedOption = 0,
                            YesNoQuestionId = 5
                        },
                        new
                        {
                            YesNoAnswerId = 6,
                            ClarUserId = "user-1",
                            SelectedOption = 1,
                            YesNoQuestionId = 6
                        },
                        new
                        {
                            YesNoAnswerId = 7,
                            ClarUserId = "user-2",
                            SelectedOption = 1,
                            YesNoQuestionId = 1
                        },
                        new
                        {
                            YesNoAnswerId = 8,
                            ClarUserId = "user-2",
                            SelectedOption = 0,
                            YesNoQuestionId = 2
                        },
                        new
                        {
                            YesNoAnswerId = 9,
                            ClarUserId = "user-2",
                            SelectedOption = 0,
                            YesNoQuestionId = 3
                        },
                        new
                        {
                            YesNoAnswerId = 10,
                            ClarUserId = "user-2",
                            SelectedOption = 1,
                            YesNoQuestionId = 4
                        },
                        new
                        {
                            YesNoAnswerId = 11,
                            ClarUserId = "user-2",
                            SelectedOption = 1,
                            YesNoQuestionId = 5
                        },
                        new
                        {
                            YesNoAnswerId = 12,
                            ClarUserId = "user-2",
                            SelectedOption = 0,
                            YesNoQuestionId = 6
                        },
                        new
                        {
                            YesNoAnswerId = 13,
                            ClarUserId = "user-3",
                            SelectedOption = 0,
                            YesNoQuestionId = 1
                        },
                        new
                        {
                            YesNoAnswerId = 14,
                            ClarUserId = "user-3",
                            SelectedOption = 1,
                            YesNoQuestionId = 2
                        },
                        new
                        {
                            YesNoAnswerId = 15,
                            ClarUserId = "user-3",
                            SelectedOption = 1,
                            YesNoQuestionId = 3
                        },
                        new
                        {
                            YesNoAnswerId = 16,
                            ClarUserId = "user-3",
                            SelectedOption = 1,
                            YesNoQuestionId = 4
                        },
                        new
                        {
                            YesNoAnswerId = 17,
                            ClarUserId = "user-3",
                            SelectedOption = 0,
                            YesNoQuestionId = 5
                        },
                        new
                        {
                            YesNoAnswerId = 18,
                            ClarUserId = "user-3",
                            SelectedOption = 1,
                            YesNoQuestionId = 6
                        },
                        new
                        {
                            YesNoAnswerId = 19,
                            ClarUserId = "user-4",
                            SelectedOption = 2,
                            YesNoQuestionId = 1
                        },
                        new
                        {
                            YesNoAnswerId = 20,
                            ClarUserId = "user-4",
                            SelectedOption = 0,
                            YesNoQuestionId = 2
                        },
                        new
                        {
                            YesNoAnswerId = 21,
                            ClarUserId = "user-4",
                            SelectedOption = 0,
                            YesNoQuestionId = 3
                        },
                        new
                        {
                            YesNoAnswerId = 22,
                            ClarUserId = "user-4",
                            SelectedOption = 1,
                            YesNoQuestionId = 4
                        },
                        new
                        {
                            YesNoAnswerId = 23,
                            ClarUserId = "user-4",
                            SelectedOption = 1,
                            YesNoQuestionId = 5
                        },
                        new
                        {
                            YesNoAnswerId = 24,
                            ClarUserId = "user-4",
                            SelectedOption = 0,
                            YesNoQuestionId = 6
                        },
                        new
                        {
                            YesNoAnswerId = 25,
                            ClarUserId = "user-5",
                            SelectedOption = 1,
                            YesNoQuestionId = 1
                        },
                        new
                        {
                            YesNoAnswerId = 26,
                            ClarUserId = "user-5",
                            SelectedOption = 0,
                            YesNoQuestionId = 2
                        },
                        new
                        {
                            YesNoAnswerId = 27,
                            ClarUserId = "user-5",
                            SelectedOption = 0,
                            YesNoQuestionId = 3
                        },
                        new
                        {
                            YesNoAnswerId = 28,
                            ClarUserId = "user-5",
                            SelectedOption = 1,
                            YesNoQuestionId = 4
                        },
                        new
                        {
                            YesNoAnswerId = 29,
                            ClarUserId = "user-5",
                            SelectedOption = 1,
                            YesNoQuestionId = 5
                        },
                        new
                        {
                            YesNoAnswerId = 30,
                            ClarUserId = "user-5",
                            SelectedOption = 1,
                            YesNoQuestionId = 6
                        });
                });

            modelBuilder.Entity("ClarifEye.Data.Models.YesNoQuestion", b =>
                {
                    b.Property<int>("YesNoQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YesNoQuestionId"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YesNoQuestionId");

                    b.ToTable("YesNoQuestions");

                    b.HasData(
                        new
                        {
                            YesNoQuestionId = 1,
                            QuestionText = "Do you wear glasses or contact lenses?"
                        },
                        new
                        {
                            YesNoQuestionId = 2,
                            QuestionText = "Do you have a family history of eye conditions?"
                        },
                        new
                        {
                            YesNoQuestionId = 3,
                            QuestionText = "Have you had eye surgery or trauma before?"
                        },
                        new
                        {
                            YesNoQuestionId = 4,
                            QuestionText = "Do you use digital screens for more than 4 hours per day?"
                        },
                        new
                        {
                            YesNoQuestionId = 5,
                            QuestionText = "Do you take regular breaks while using screens?"
                        },
                        new
                        {
                            YesNoQuestionId = 6,
                            QuestionText = "Are you currently experiencing any vision-related problems?"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClarifEye.Data.Models.ClarUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Enum")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFilled")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ClarUser");

                    b.HasData(
                        new
                        {
                            Id = "user-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57a86388-9a4a-4a05-811b-62cdcb95ae0b",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1459bf77-0e1e-4f1b-9d2a-9b660638119e",
                            TwoFactorEnabled = false,
                            Age = 34,
                            Enum = 0,
                            FirstName = "Ivan",
                            IsFilled = false,
                            LastName = "Dimitrov",
                            Occupation = "Software Engineer"
                        },
                        new
                        {
                            Id = "user-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c02952f7-9d5a-42c9-b126-77a648b18391",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a2c6c286-2864-4801-a25f-e7656900923c",
                            TwoFactorEnabled = false,
                            Age = 28,
                            Enum = 1,
                            FirstName = "Maria",
                            IsFilled = false,
                            LastName = "Petrova",
                            Occupation = "Graphic Designer"
                        },
                        new
                        {
                            Id = "user-3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "27a63e97-24a5-4994-83b2-853aa8e912d1",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1e518357-277d-4cdc-acc2-62707d5616d7",
                            TwoFactorEnabled = false,
                            Age = 45,
                            Enum = 0,
                            FirstName = "Georgi",
                            IsFilled = false,
                            LastName = "Ivanov",
                            Occupation = "Teacher"
                        },
                        new
                        {
                            Id = "user-4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0e0ec446-cf47-4a8c-8cb7-f0a9e55653d1",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c931a4fd-2846-40d0-a935-7e2471bbdc8c",
                            TwoFactorEnabled = false,
                            Age = 22,
                            Enum = 1,
                            FirstName = "Elena",
                            IsFilled = false,
                            LastName = "Koleva",
                            Occupation = "Student"
                        },
                        new
                        {
                            Id = "user-5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9e7721a2-c993-46d6-931f-a5a73d02dfa7",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "94f1ca17-5537-45bd-b49b-f845330d52ed",
                            TwoFactorEnabled = false,
                            Age = 39,
                            Enum = 0,
                            FirstName = "Nikolay",
                            IsFilled = false,
                            LastName = "Stoyanov",
                            Occupation = "Mechanic"
                        });
                });

            modelBuilder.Entity("ClarifEye.Data.Models.Choice", b =>
                {
                    b.HasOne("ClarifEye.Data.Models.MultipleChoiceQuestion", "MultipleChoiceQuestion")
                        .WithMany()
                        .HasForeignKey("MultipleChoiceQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MultipleChoiceQuestion");
                });

            modelBuilder.Entity("ClarifEye.Data.Models.ChoiceAnswer", b =>
                {
                    b.HasOne("ClarifEye.Data.Models.Choice", "Choice")
                        .WithMany()
                        .HasForeignKey("ChoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClarifEye.Data.Models.ClarUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Choice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClarifEye.Data.Models.ScaleAnswer", b =>
                {
                    b.HasOne("ClarifEye.Data.Models.ClarUser", "User")
                        .WithMany()
                        .HasForeignKey("ClarUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClarifEye.Data.Models.ScaleQuestion", "ScaleQuestion")
                        .WithMany()
                        .HasForeignKey("ScaleQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScaleQuestion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClarifEye.Data.Models.YesNoAnswer", b =>
                {
                    b.HasOne("ClarifEye.Data.Models.ClarUser", "User")
                        .WithMany()
                        .HasForeignKey("ClarUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClarifEye.Data.Models.YesNoQuestion", "YesNoQuestion")
                        .WithMany()
                        .HasForeignKey("YesNoQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("YesNoQuestion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
